sudo: false
language: node_js
node_js:
  - 8
  - 9
  - 10
  - stable

cache:
  bundle: true
  directories:
    - node_modules

#install:
# - npm install

jobs:
  include:
    #    - stage: Document deploy
    #      allow_failure: true
    #      script: npm run site:build
    #      deploy:
    #        provider: pages
    #        skip_cleanup: true
    #        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
    #        local_dir: _site/public
    - stage: Unit testing
      before_script: npm install codecov --no-save
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
